### PR TITLE
Dynamic Experience Years

### PR DESCRIPTION
**Pull request by agrajagrawal**
#### Just Made Experience Years of your skills section Dynamic which automatically changes as the year changes so that you don't need to update it every year!!

### CODE REVIEW

**Comment by maskmanlucifer** [comment]
Thanks for your contribution @agrajagrawal.
Happy Hacking :)

**Comment by maskmanlucifer** [comment]
@agrajagrawal i think there will be some problem will this PR.
Since the portfolio is hosted on github pages and github pages hosts static sites , it basically precalulate all ui parameters and renders that statically.
You code will work if i will host my site dynamically so that time gap etc calculation  can be done on browser side but for now your code will not inject any value in static html.

**Comment by maskmanlucifer** [comment]
We can discuss if you have any doubt.

**Comment by agrajagrawal** [comment]
Is this with gh-pages only or does Heroku and other hosting sites also don't support this?
Previously I have tried EJS with the server-side script and it works fine for rendering dynamic elements in HTML!
Is this an issue because client-side script?

**Comment by maskmanlucifer** [comment]
Every hosting service which host's static sites follow almost same strategy.
This will not be an issue with server side hosting platforms same site hosted on heroku will work fine with your code.

**Comment by agrajagrawal** [comment]
Okay Thanks! Today I got to know that gh-pages is only a static hosting service.

**Pull request merged**
